// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "okd.dev"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "okd.dev.bdreporting.local"

// Base domain from which the cluster domain is a subdomain.
base_domain = "bdreporting.local"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.bdreporting.local".
vsphere_server = "vcenter.bdreporting.local"

// User on the vSphere server.
vsphere_user = "YOUR_USER"

// Password of the user on the vSphere server.
vsphere_password = "YOUR_PASSWORD"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "YKTNESX"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "YKT"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "/YKT/NP/OpenShift/YKTNSAN01-NESX-OPENSHIFT-VMS-02"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "fedora - coreos - 32.20200923.3.0"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID.
machine_cidr = "10.0.0.0/24"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 3

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://10.33.153.87:8080/install/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"merge":[{"source":"https://api-int.okd.dev.bdreporting.local:22623/config/master","verification":{}}],"replace":{"verification":{}}},"proxy":{},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJWXQyem1PMjBJVlF3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TVRBeE5ERXlNVEF4TUZvWApEVE13TVRBeE1qRXlNVEF4TUZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1azBNMnovY2MxQ3oKVlBrRituenZkWVZ2Zy90N0RUcjVFd3lISXFyZENMcG9EVEpHLzhqYzBXcG5UdElqOWlNV2ZFOWpMa3JpR1B2MwpReHIySE8ybGI1QkM1aXBHVkZIR20xOTcyWk5jN3c0WjcrQnpwQkpNcDRmYVBvcGEyR1IzKzJOOEUxY2VHSklqCkdFYWRFOStmSlN4WlFIcHdQN0NjczR6RmJpdmJZaUppWDl1S3QzME9Mc1JxVi85eVJQTmtiV05neFY2L2VhdGYKb2lNQ0xuY3dIYXlySFF3Myt1eU1DWElqUzVLUDRNeUN0MzYrWmJWV2hsbDQrZmNpMjJUQUFENE8rMnI5V3RTMAoyY253eUFUR3hsZ3ZLbDRocmI0N1hLaWtEWUZBaHZLWmhKd2g2VUN4aU1ETVNFbG9BMnNHSncyYUVEcHN6N2I0Ck5ZQmFEQWs3UndJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVJlU1lUUmg3YzRWVWovamtCWjgrZFNxaEJHc3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUN1K3lMZXljbG1JczRvS0hCdlovYTVCcUtmTlh5bUdFcHdMTUs4NkpTdi92QzVPMytMYWVwVUhpd1VWCk9vK3Z0UGtGUFA4K0RVcnVObWR2TXRVdmorNkJzRjJQTWs5WHNaL053MTA1aWFlR3B0bTZBVzVUNXNnZkcwbXoKRUwrdXNGS2NyQlNjUk9Ma1YreWVYeldpbnhTWUFIeUxPbEZBakw1U2pWVnlEdHM5dEtSanEvclV4MkZiQSs3Qgo0YzU3QWJBMndzbTJEVGx3cXRSUFN5aHFJM2tZbWJpSEEzWGEwVEwyTlRqVFZqbG0vQy81Y0VFTGNzd2I1NTdxCjVHVlIrUkxZNUVOSTFidGYyWEFiOXFpUzhkV1BlOGVpSUhlWkpQL3N6NFgrT0taS1ZyVXZpeGU0NTFPTDN5WVIKQTJUV2w4TU5OMmgwdzRpL2pjWjRmengzNldZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"3.1.0"},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"merge":[{"source":"https://api-int.okd.dev.bdreporting.local:22623/config/worker","verification":{}}],"replace":{"verification":{}}},"proxy":{},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJWXQyem1PMjBJVlF3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TVRBeE5ERXlNVEF4TUZvWApEVE13TVRBeE1qRXlNVEF4TUZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1azBNMnovY2MxQ3oKVlBrRituenZkWVZ2Zy90N0RUcjVFd3lISXFyZENMcG9EVEpHLzhqYzBXcG5UdElqOWlNV2ZFOWpMa3JpR1B2MwpReHIySE8ybGI1QkM1aXBHVkZIR20xOTcyWk5jN3c0WjcrQnpwQkpNcDRmYVBvcGEyR1IzKzJOOEUxY2VHSklqCkdFYWRFOStmSlN4WlFIcHdQN0NjczR6RmJpdmJZaUppWDl1S3QzME9Mc1JxVi85eVJQTmtiV05neFY2L2VhdGYKb2lNQ0xuY3dIYXlySFF3Myt1eU1DWElqUzVLUDRNeUN0MzYrWmJWV2hsbDQrZmNpMjJUQUFENE8rMnI5V3RTMAoyY253eUFUR3hsZ3ZLbDRocmI0N1hLaWtEWUZBaHZLWmhKd2g2VUN4aU1ETVNFbG9BMnNHSncyYUVEcHN6N2I0Ck5ZQmFEQWs3UndJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVJlU1lUUmg3YzRWVWovamtCWjgrZFNxaEJHc3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUN1K3lMZXljbG1JczRvS0hCdlovYTVCcUtmTlh5bUdFcHdMTUs4NkpTdi92QzVPMytMYWVwVUhpd1VWCk9vK3Z0UGtGUFA4K0RVcnVObWR2TXRVdmorNkJzRjJQTWs5WHNaL053MTA1aWFlR3B0bTZBVzVUNXNnZkcwbXoKRUwrdXNGS2NyQlNjUk9Ma1YreWVYeldpbnhTWUFIeUxPbEZBakw1U2pWVnlEdHM5dEtSanEvclV4MkZiQSs3Qgo0YzU3QWJBMndzbTJEVGx3cXRSUFN5aHFJM2tZbWJpSEEzWGEwVEwyTlRqVFZqbG0vQy81Y0VFTGNzd2I1NTdxCjVHVlIrUkxZNUVOSTFidGYyWEFiOXFpUzhkV1BlOGVpSUhlWkpQL3N6NFgrT0taS1ZyVXZpeGU0NTFPTDN5WVIKQTJUV2w4TU5OMmgwdzRpL2pjWjRmengzNldZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"3.1.0"},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION


// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
//ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
//ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
bootstrap_ip = "10.33.153.124"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
control_plane_ips = ["10.33.153.119", "10.33.153.120", "10.33.153.121"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
compute_ips = ["10.33.153.122", "10.33.153.123"]
